FROM python:3.10-buster

WORKDIR /app
RUN apt update && apt install python-magic yara libyara-dev ssdeep build-essential libffi-dev libfuzzy-dev -y
RUN pip install ssdeep pymysql yara-python python-magic boto3 python-dotenv
COPY lib /app/lib
COPY Yaggy /app/Yaggy
COPY upload_handler.py /app/
COPY .env /app/
CMD python3 -u upload_handler.py
