FROM python:3.14

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
        libmariadb-dev build-essential \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir mariadb boto3
COPY lib /app/lib
COPY backfill_sizes.py /app/
CMD ["python3", "-u", "backfill_sizes.py"]
