FROM ghcr.io/malshare/pymalshare-base:latest

RUN apt-get update && apt-get install -y --no-install-recommends tor \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir "requests[socks]"
COPY lib /app/lib
COPY url_task_handler.py /app/
COPY docker/entrypoint-url-task-handler.sh /app/
RUN chmod +x /app/entrypoint-url-task-handler.sh
CMD ["/app/entrypoint-url-task-handler.sh"]
